### ISSUE TITLE
Don't work with node v10.2.1

### ISSUE THREAD

**Issue by fais3000** [anpandu/nodejs-text-summarizer#2]
Fails at the following error
```
node_modules/nodejs-text-summarizer/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26
logger.setLevel('WARN');

TypeError: logger.setLevel is not a function
```

**Comment by sheksushant** [comment]
@anpandu is any FIX coming?

**Comment by rahulkathet** [comment]
> @anpandu is any FIX coming?

Go to **node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js**

replace comment **logger.setLevel('WARN');**

And add **logger.level = 'DEBUG';**

**Comment by rahulkathet** [comment]
> Fails at the following error
> 
> ```
> node_modules/nodejs-text-summarizer/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26
> logger.setLevel('WARN');
> 
> TypeError: logger.setLevel is not a function
> ```

Go to **node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js**

replace comment **logger.setLevel('WARN');**

And add **logger.level = 'DEBUG';**
